version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout

      # Bundle install dependencies
      - run: bundle install './Gemfile'

      # Save test results for timing analysis
      - store_test_results:
          path: test_results